site_name: Sidharth
theme:
  name: material
  features:
  #  - navigation.footer
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - content.code.copy
    - content.code.annotate 
    - content.code.select
    - toc.integrate
    
  #  - search.highlight
  palette:
    scheme: slate
    primary: black
    accent: indigo

nav:
- Home: index.md
- Notebook page: Perceptron.ipynb
- Assignment: VAE MNIST.ipynb


extra:
  generator: false

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid

  
  - toc:
      title: Summary
      
  - pymdownx.arithmatex:
      generic: true
  


plugins:
  #- mkdocs-jupyter:
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
      #enable_default_pandas_dataframe_styling: false
      

copyright: Copyright &copy;2024 Sidharth Padmanabhan
